In [ ]:
import torch

# Create a tensor
x = torch.arange(12, dtype=torch.float32)
print(f"Original tensor x: {x}")

# Storage is a 1D array of 12 floats
print(f"Storage elements: {x.storage().tolist()}")
print(f"Storage type: {x.storage().dtype}")
print(f"Storage size: {len(x.storage())}")

# Create a view by reshaping
y = x.view(3, 4)
print(f"\nReshaped tensor y:\n{y}")

# y has different shape/strides but shares the same storage
print(f"Does y share storage with x? {y.storage().data_ptr() == x.storage().data_ptr()}")

# Modifying the view affects the original (and vice versa)
y[0, 0] = 99.0
print(f"\nModified y:\n{y}")
print(f"Original x after modifying y: {x}")

Original tensor x: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
Storage elements: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0]
Storage type: torch.float32
Storage size: 12

Reshaped tensor y:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Does y share storage with x? True

Modified y:
tensor([[99.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Original x after modifying y: tensor([99.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


/var/folders/t0/jgz4s8zs4rb10n6q9c7x25sm0000gn/T/ipykernel_37875/1814039797.py:8: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(f"Storage elements: {x.storage().tolist()}")


In [9]:
t = torch.arange(12, dtype=torch.float32)
print(f"Tensor t:\n{t}")
print(f"Shape: {t.shape}")
print(f"Stride: {t.stride()}")

Tensor t:
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
Shape: torch.Size([12])
Stride: (1,)


In [13]:
t = torch.arange(12, dtype=torch.float32).view(3, 4)
print(f"Tensor t:\n{t}")
print(f"Shape: {t.shape}")
print(f"Stride: {t.stride()}")

Tensor t:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Shape: torch.Size([3, 4])
Stride: (4, 1)


In [12]:
t_transposed = t.t() # Transpose operation
print(f"\nTransposed tensor t_transposed:\n{t_transposed}")
print(f"Shape: {t_transposed.shape}")
print(f"Stride: {t_transposed.stride()}")
print(f"Is t_transposed contiguous? {t_transposed.is_contiguous()}") # Output: False
print(f"Does t_transposed share storage with t? {t_transposed.storage().data_ptr() == t.storage().data_ptr()}") # Output: True


Transposed tensor t_transposed:
tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])
Shape: torch.Size([4, 3])
Stride: (1, 4)
Is t_transposed contiguous? False
Does t_transposed share storage with t? True
