In [37]:
import torch
torch.set_printoptions(precision=2, sci_mode=False)
import numpy as np


In [38]:
def load_tensor(filename):
    metadata = {}
    data_values = []
    
    # List of metadata keys to look for
    meta_keys = ['size', 'ndim', 'shape', 'stride', 'elem_size', 'requires_grad']

    with open(filename, 'r') as f:
        for line in f:
            # Clean up line: remove spaces, split by comma
            parts = [p.strip() for p in line.split(',') if p.strip()]
            
            if not parts:
                continue  # Skip empty lines
            
            # Check if this row starts with a metadata label
            label = parts[0]
            
            if label in meta_keys:
                # If there are numbers after the label, store them
                vals = [int(v) for v in parts[1:]]
                metadata[label] = vals[0] if len(vals) == 1 else vals
            else:
                # If it's not a label, check if the parts are numbers (the tensor data)
                try:
                    row_data = [float(p) for p in parts]
                    data_values.extend(row_data)
                except ValueError:
                    # Not a number and not a metadata key (could be a header or text)
                    continue

    # Convert to PyTorch Tensor
    if 'shape' in metadata:
        # Convert floats to ints for reshaping (e.g., 2.0 -> 2)
        target_shape = [int(s) for s in metadata['shape']]
        tensor = torch.tensor(data_values).reshape(target_shape)
        return metadata, tensor
    
    return metadata, torch.tensor(data_values)

In [39]:
meta_tensor1, tensor1 = load_tensor('../output/tensor1.csv')
meta_tensor2, tensor2 = load_tensor('../output/tensor2.csv')
meta_output_tensor, output_tensor_c = load_tensor('../output/output_tensor.csv')

In [40]:
print("Metadata:", meta_tensor1)
display(tensor1)
print("Metadata:", meta_tensor2)
display(tensor2)
print("Metadata:", meta_output_tensor)
display(output_tensor_c)

Metadata: {'size': 24, 'ndim': 2, 'shape': [6, 4], 'stride': [4, 1], 'elem_size': 8, 'requires_grad': 0}


tensor([[-10.00,  -7.37,   5.11,  -0.83],
        [  0.66,  -5.62,  -9.06,   3.58],
        [  3.59,   8.69,  -2.33,   0.39],
        [  6.62,  -9.31,  -8.93,   0.59],
        [  3.42,  -9.85,  -2.33,  -8.66],
        [ -1.65,   3.74,   1.78,   8.61]])

Metadata: {'size': 24, 'ndim': 2, 'shape': [4, 6], 'stride': [6, 1], 'elem_size': 8, 'requires_grad': 0}


tensor([[ 6.92,  0.54, -8.16,  3.08, -1.68,  4.02],
        [ 8.21,  5.24, -4.75, -9.05,  4.72, -3.44],
        [ 2.65,  5.13,  9.82, -2.69, -5.06,  9.65],
        [ 4.45,  5.07,  3.03, -8.55,  2.63,  7.69]])

Metadata: {'size': 36, 'ndim': 2, 'shape': [6, 6], 'stride': [6, 1], 'elem_size': 8, 'requires_grad': 0}


tensor([[-119.83,  -22.00,  164.32,   29.21,  -46.04,   28.05],
        [ -49.69,  -57.45,  -56.77,   46.72,   27.61,  -37.96],
        [  91.72,   37.54,  -92.27,  -64.69,   47.83,  -34.94],
        [ -51.61,  -88.04,  -95.70,  123.60,   -8.33,  -23.01],
        [-101.87, -105.64,  -30.31,  179.97,  -63.25,  -41.56],
        [  62.29,   71.45,   39.28, -117.25,   34.07,   63.94]])

In [41]:
tensor1.shape

torch.Size([6, 4])

In [42]:
tensor2.shape

torch.Size([4, 6])

In [43]:
output_tensor_py = tensor1 @ tensor2
output_tensor_py.shape

torch.Size([6, 6])

In [44]:
output_tensor_py

tensor([[-119.86,  -22.01,  164.27,   29.25,  -46.03,   28.08],
        [ -49.65,  -57.42,  -56.81,   46.66,   27.62,  -37.91],
        [  91.75,   37.50,  -92.27,  -64.65,   47.80,  -34.95],
        [ -51.66,  -88.03,  -95.70,  123.62,   -8.33,  -23.00],
        [-101.91, -105.63,  -30.24,  179.99,  -63.22,  -41.45],
        [  62.32,   71.49,   39.27, -117.33,   34.06,   63.89]])

In [45]:
output_tensor_c

tensor([[-119.83,  -22.00,  164.32,   29.21,  -46.04,   28.05],
        [ -49.69,  -57.45,  -56.77,   46.72,   27.61,  -37.96],
        [  91.72,   37.54,  -92.27,  -64.69,   47.83,  -34.94],
        [ -51.61,  -88.04,  -95.70,  123.60,   -8.33,  -23.01],
        [-101.87, -105.64,  -30.31,  179.97,  -63.25,  -41.56],
        [  62.29,   71.45,   39.28, -117.25,   34.07,   63.94]])

In [46]:
output_tensor_py - output_tensor_c

tensor([[-0.03, -0.01, -0.05,  0.04,  0.01,  0.03],
        [ 0.04,  0.03, -0.04, -0.06,  0.01,  0.05],
        [ 0.03, -0.04, -0.00,  0.04, -0.03, -0.01],
        [-0.05,  0.01, -0.00,  0.02,  0.00,  0.01],
        [-0.04,  0.01,  0.07,  0.02,  0.03,  0.11],
        [ 0.03,  0.04, -0.01, -0.08, -0.01, -0.05]])

In [47]:
output_tensor_py.shape

torch.Size([6, 6])

In [11]:
output_tensor_c.shape

torch.Size([2, 4, 4])